- styles/all/template/event/memberlist_view_content_append.html
- styles/all/template/event/memberlist_view_content_prepend.html
- styles/all/template/event/overall_footer_after.html
- styles/all/template/event/overall_footer_page_body_after.html
- styles/all/template/event/overall_header_body_before.html
- styles/all/template/event/overall_header_navbar_before.html
- styles/all/template/event/viewtopic_body_poll_after.html
- styles/all/template/event/viewtopic_body_postrow_post_after.html
- styles/all/template/event/viewtopic_body_topic_actions_before.html
- styles/all/theme/admanagement.css
- tests/functional/location_below_footer_test.php
> #6: Ad margins need flexibility

- styles/all/template/event/memberlist_view_content_append.html
- styles/all/template/event/memberlist_view_content_prepend.html
- styles/all/template/event/overall_footer_after.html
- styles/all/template/event/overall_footer_page_body_after.html
- styles/all/template/event/overall_header_body_before.html
- styles/all/template/event/overall_header_navbar_before.html
- styles/all/template/event/viewtopic_body_poll_after.html
- styles/all/template/event/viewtopic_body_postrow_post_after.html
- styles/all/template/event/viewtopic_body_topic_actions_before.html
> #7: Flex box has undesired results with some text

- migrations/v10x/m5_end_date.php
> #13: End Date migration has wrong effectively_installed() check

- controller/admin_controller.php
> #10: Merge get_form_data() and validate()

- acp/main_info.php
- acp/main_module.php
- ad/manager.php
- adm/style/settings_ads.html
- config/services.yml
- controller/admin_controller.php
- event/main_listener.php
- language/en/acp.php
- language/en/info_acp_admanagement.php
- migrations/v10x/m6_hide_for_group.php
- tests/acp/acp_module_test.php
- tests/controller/admin_controller_test.php
- tests/event/main_listener_base.php
- tests/event/setup_ads_test.php
- tests/fixtures/ad.xml
- tests/functional/acp_test.php
- tests/functional/hide_group_test.php
Admin can specify groups advertisement will not be displayed to.
> Hide advertisement for specific group

- controller/admin_controller.php
> Fix minor issue with end date return type

- migrations/v10x/m1_initial_schema.php
- migrations/v10x/m3_template_locations_schema.php
- migrations/v10x/m4_indexes.php
- migrations/v10x/m5_end_date.php
- migrations/v10x/m6_hide_for_group.php
> #19: Unable to purge (delete data) extension

- adm/style/manage_ads.html
> #23: Set colspan to 4

- acp/main_info.php
- adm/style/event/acp_overall_footer_after.html
- adm/style/event/acp_overall_header_head_append.html
- adm/style/manage_ads.html
- build.xml
- controller/admin_controller.php
- language/en/info_acp_phpbb_ads.php
- migrations/v10x/m2_acp_module.php
- migrations/v10x/m6_hide_for_group.php
- tests/acp/acp_module_test.php
- tests/controller/admin_controller_test.php
- tests/fixtures/ad.xml
- tests/functional/acp_test.php
- tests/functional/functional_base.php
> #26: Get rid of admanagement completely

- adm/style/settings_ads.html
- config/services.yml
- controller/admin_controller.php
- event/main_listener.php
- language/en/acp.php
- language/en/common.php
- migrations/v10x/m7_adblocker.php
- styles/all/template/event/overall_header_content_before.html
- tests/controller/admin_controller_test.php
- tests/event/load_language_on_setup_test.php
- tests/event/main_listener_base.php
- tests/event/main_listener_test.php
- tests/event/setup_ads_test.php
- tests/functional/acp_test.php
- tests/functional/adblocker_test.php
Admin can decide on displaying friendly message on locations where AdBlocker hides advertisements.
https://trello.com/c/L4D5Bwvx/7-adblocker-friendly-message
> AdBlocker friendly message

- adm/style/manage_ads.html
- styles/all/template/event/memberlist_view_content_append.html
- styles/all/template/event/memberlist_view_content_prepend.html
- styles/all/template/event/overall_footer_after.html
- styles/all/template/event/overall_footer_page_body_after.html
- styles/all/template/event/overall_header_body_before.html
- styles/all/template/event/overall_header_navbar_before.html
- styles/all/template/event/viewtopic_body_poll_after.html
- styles/all/template/event/viewtopic_body_postrow_post_after.html
- styles/all/template/event/viewtopic_body_topic_actions_before.html
- styles/all/template/phpbb_ads_default.html
- styles/all/theme/phpbbads.css
Fixes #29 
@senky can you test and see what you think
> Make sure ads use full width of enclosing div

- adm/style/settings_ads.html
- language/en/acp.php
> #36: Adblock Plus hides enable radio button for Ad blocker friendly message

- ad/manager.php
- tests/ad/get_ads_test.php
- tests/fixtures/ad.xml
What do you think of this test for really testing that priority works?
> Improve and fix ad priority

- tests/ad/ad_base.php
- tests/ad/get_ads_test.php
- tests/controller/admin_controller_test.php
- tests/fixtures/ad.xml
This PR completes the get_ads() test I started.
> Test updates

- tests/ad/delete_ad_locations_test.php
- tests/ad/delete_ad_test.php
- tests/ad/get_ad_locations_test.php
- tests/ad/get_ad_test.php
- tests/ad/get_all_ads_test.php
- tests/ad/insert_ad_locations_test.php
- tests/ad/insert_ad_test.php
- tests/ad/load_groups_test.php
- tests/ad/load_memberships_test.php
- tests/ad/update_ad_test.php
- tests/controller/admin_controller_test.php
- tests/fixtures/ad.xml
- tests/location/get_all_location_ids_test.php
- tests/location/get_all_locations_test.php
- tests/location/location_base.php
> #33: Tests should be refactored (eventually)

- adm/style/manage_ads.html
> #44: Make 5 a default value in priority field

- ad/manager.php
- event/main_listener.php
- tests/ad/remove_ad_owner_test.php
- tests/event/main_listener_test.php
- tests/event/remove_ad_owner_test.php
- tests/fixtures/ad.xml
> #51: Add event to user delete where we remove the user's ID from our AD too

- adm/style/manage_ads.html
- banner/banner.php
- config/services.yml
- controller/admin_controller.php
- controller/admin_helper.php
- controller/admin_input.php
- tests/banner/banner_base.php
- tests/banner/create_storage_dir_test.php
- tests/banner/remove_test.php
- tests/banner/upload_test.php
- tests/controller/admin_controller_test.php
- tests/controller/admin_helper_test.php
- tests/controller/admin_input_test.php
> #50: Refactor admin controller

- event/main_listener.php
> #65: Improve precise views

- ad/manager.php
- adm/style/manage_ads.html
- controller/admin_controller.php
- language/en/acp.php
- tests/controller/admin_controller_test.php
https://trello.com/c/NaLWqyQJ/23-acp-ad-management-improvements
> ACP Ad Management Improvements

- language/en/acp.php
> #80: Slide up explain

- tests/location/get_all_location_ids_test.php
- tests/location/location_base.php
> Add some more test coverage

- event/main_listener.php
- tests/event/adblocker_test.php
> Only display ad blocker msg to users who can view ads

- migrations/v10x/m10_ad_owner_schema.php
- migrations/v10x/m9_views_clicks.php
- tests/functional/zbase_test.php
> Fix migrations again for delete data

- language/en/acp.php
I'm not sure, but...
Copy/paste error for clicks/views ?
Best regards.
> Small change

- styles/all/template/event/viewtopic_body_postrow_post_after.html
- tests/functional/locations_test.php
https://trello.com/c/PEuUIoQC/53-display-after-first-post-only-if-topic-has-reply
> Display After First Post only if topic has reply

- composer.json
- config/services.yml
- controller/admin_controller.php
- event/main_listener.php
- language/en/permissions_ads.php
- migrations/v10x/m12_u_phpbb_ads_permission.php
- tests/controller/admin_controller_test.php
- tests/event/main_listener_test.php
- tests/event/set_permissions_test.php
- tests/functional/ucp_test.php
- tests/ucp/ucp_module_test.php
- ucp/main_info.php
> #103: Hide UCP module for members without ads

- ad/manager.php
As noticed in one [support topic](https://www.phpbb.com/customise/db/extension/ads/support/topic/185951), SQL query for getting ads is overcomplicated. Simplifying also seems to fix randomness problem for [some](https://www.phpbb.com/customise/db/extension/ads/support/topic/185951?p=606311#p606311) [users](https://www.phpbb.com/customise/db/extension/ads/support/topic/185951?p=611816#p611816).
> Simplify SQL query in get_ads

- controller/admin_controller.php
- tests/controller/admin_controller_test.php
> #106: Display ads list when you don't confirm ad deleting

- migrations/v10x/m12_u_phpbb_ads_permission.php
> #117: UCP tab is not updated in migration

- styles/all/theme/phpbbads.css
Fixes https://www.phpbb.com/customise/db/extension/ads/support/topic/191151
This is very quick fix that should be released ASAP. But whole ad location styling is broken. We should rethink it and strictly define what is our responsibility and what is responsibility of users. This situation is unsustainable.
> Fix script content displayed

- styles/all/theme/phpbbads.css
> Re-style the visual demo ads

- ad/manager.php
> Fix get_ads() with empty result from DB

- config/services.yml
- event/main_listener.php
- tests/event/destroy_user_group_cache_test.php
- tests/event/main_listener_base.php
- tests/event/main_listener_test.php
Fixes https://www.phpbb.com/customise/db/extension/ads/support/topic/203056
> Destroy cache when user groups are changed

- event/main_listener.php
- tests/functional/content_only_test.php
Add memberlist and viewonline as non-content pages, since these are just lists of members.
> Add more non content pages

- controller/helper.php
- tests/controller/helper_test.php
> Retain selected groups on preview

- styles/all/template/includes/phpbb_ads_pop_up.html
> Escape last in filter chains

- ad/manager.php
Discovered oracle queries failed. This should fix.
> Fix Oracle Query

- .github/workflows/tests.yml
- adm/style/manage_ads.html
- language/en/acp.php
- language/en/common.php
- styles/all/template/includes/ad_visual_demo_notice.html
- styles/all/theme/phpbbads.css
Make it look more like this. Ads a different color than the button. And the button a little more obvious too.
> Visual demo improvements

- event/main_listener.php
- tests/event/setup_ads_test.php
- tests/event/views_test.php
- tests/functional/content_only_test.php
> Add ADM to non content pages

- CHANGELOG.md
- composer.json
Signed-off-by: Matt Friedman <maf675@gmail.com>
> Bump version to 3.0.0

- composer.json
- config/location.yml
- config/services.yml
- event/main_listener.php
- language/en/ucp.php
- location/type/pop_up.php
- styles/all/template/includes/phpbb_ads_pop_up.html
- tests/event/amend_agreement_test.php
- tests/event/main_listener_base.php
- tests/functional/ucp_test.php
- tests/location/get_all_location_ids_test.php
- tests/location/location_base.php
Update privacy policy of forums regarding adverts. Also took opportunity to replace a cookie with local browser storage via JS when closing the pop-up ad type.
> Amend privacy policy regarding ads
